version: '3.5'
services:
  postgres:
    image: postgres:12.3
    container_name: test-postgres
    restart: always
    environment:
      - POSTGRES_DB=eureka-persons
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - GRANT ALL PRIVILEGES ON DATABASE persons TO postgresTest;
    ports:
      - "5435:5432"

  keyclock:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev