services:
  network-deploy-service:
    networks:
      - mynetwork

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      EUREKA.PATH.CONFIG: "http://eureka-server:8761/"

  microservice-common-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      CONFIG.PATH: "http://configserver:8072/"