version: '3.5'
services:
  postgres:
    image: postgres:12.3
    container_name: postgres
    environment:
      - POSTGRES_DB=eureka-persons
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yml
      service: network-deploy-service

  redis:
    image: redis
    container_name: redisForGateway
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "eureka/configserver:v1"
    container_name: config-server
    ports:
      - "8072:8072"
    healthcheck:
      test: curl --fail http://localhost:8072/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eureka-server:
    image: "eureka/eureka-server:v1"
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: curl --fail http://localhost:8072/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"
    extends:
      file: common-config.yml
      service: microservice-common-config

  persons-server:
    image: "eureka/person-service:v1"
    container_name: persons-server
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_NAME: "persons"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "password"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8085/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: microservice-common-config

  notes-server:
    image: "eureka/notes-service:v1"
    container_name: noteservice-server
    ports:
      - "8885:8885"
    environment:
      SPRING_APPLICATION_NAME: "notes"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8885/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: microservice-common-config

  accounts-server:
    image: "eureka/accounts:v1"
    container_name: accounts-server
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    healthcheck:
      test: curl --fail http://localhost:8089/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: microservice-common-config

  gateway-server:
    image: "eureka/gateway:v1"
    container_name: gatewayservice-server
    ports:
      - "8887:8887"
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: "2s"
      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_DATA_REDIS_TIMEOUT: "1s"
    depends_on:
      persons-server:
        condition: service_healthy
      notes-server:
        condition: service_healthy
      accounts-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-common-config

networks:
  mynetwork:
    driver: "bridge"
